### ISSUE TITLE
Increasing 503 error codes over time

### ISSUE THREAD

**Issue by mcasperson** [voyagermesh/voyager#1334] opened 2019-01-30 23:59 UTC
We have a cluster that has experienced an error where requests increasingly return 503 HTTP codes over time.

The image below shows the errors generated by requests to a K8S cluster with Voyager. This cluster was up for a number of days, and then starting at 11:00 requests started returning 503 (ignore the peak around 9:00, that was an unrelated problem). At about 15:30 the Voyager ingress controller pods were deleted and restarted, and the errors went away.

We had 2 Voyager ingress controller pods, which would explain the zigzag pattern as each pod returns more (but not the same number of) 503 response codes.

![image](https://user-images.githubusercontent.com/160104/52020726-288c6380-253e-11e9-925b-d42c3b8fbd46.png)

I've experienced this problem a few times since, and deleting the Voyager pods always resolves the issue with no additional changes to the cluster.

The log files from the Voyager ingress controller pods don't show anything that indicates an error, other than listing the 503 error responses themselves.

I can set up a cron job to recycle the Voyager pods easily enough, which does seem to prevent the problem from happening.

So I have two questions:
1. Has anyone else experienced these 503 errors?
2. Is there any downside to using cron to delete the Voyager ingress controller pods?

We are using Voyager 7.40 in AKS, and routing TCP and HTTP traffic.

**Comment by mkozjak** [comment] 2019-05-15 15:46
Happened again. We're using Google Kubernetes Engine with Voyager 9.0.0.

**Comment by kfoozminus** [comment] 2019-05-27 09:34
@mkozjak `For some reason voyager ingress still sends requests to terminated backend pods, even though they aren't in /etc/haproxy/haproxy.cfg anymore.` - How did you check that? By doing exec to the voyager pod or by describing the ingress's configmap?

**Comment by mkozjak** [comment] 2019-05-27 11:39
@kfoozminus ingress' configmap values were updated. `haproxy.cfg` was ok too (yes, exec'd). I tailed voyager pod logs and it'd still hit backend pods that weren't alive anymore.

**Comment by kfoozminus** [comment] 2019-05-27 14:45
@mkozjak Does this problem after a certain period of time automatically? Or do you have to delete the controller pod every time?

I'm trying to reproduce the problem. Any details that can help me do that is much appreciated :)

**Comment by mkozjak** [comment] 2019-05-27 14:58
@kfoozminus You mean does it go away? No. And it starts happening automatically in random intervals. Maybe @mcasperson has more info.

**Comment by kfoozminus** [comment] 2019-05-27 15:05
@mcasperson 
> I've experienced this problem a few times since, and deleting the Voyager pods always resolves the issue with no additional changes to the cluster.

Does this problem never go away? Or it takes too long to be fixed up so you just delete the pod to avoid down time?

**Comment by kfoozminus** [comment] 2019-05-27 15:15
@mkozjak 

> And it starts happening automatically in random intervals. 

So here's what I gathered:
- You had a working voyager ingress with (let's say) one backend service which has 4 pods.
- You updated the backend deployment. So all of your 4 pods are terminated and 4 new are created.
- Ingress-configmap and `/etc/haproxy/haproxy.cfg` inside the ingress-pod shows updated configuration, but your log shows traffic is going to terminated pods.
- This problem never go away. You restart the ingress-pod (the one generated from Ingress object) and everything works well.

Is that ok?

@mcasperson Same like this?

**Comment by mkozjak** [comment] 2019-05-29 05:26
@kfoozminus all good, except that the traffic also goes to new ones. Sometimes it chooses new ones and sometimes old ones.

**Comment by kfoozminus** [comment] 2019-05-29 05:48
> @kfoozminus all good, except that the traffic also goes to new ones. Sometimes it chooses new ones and sometimes old ones (3rd bullet).

But the haproxy.cfg contains **only** the new pods?

**Comment by mkozjak** [comment] 2019-05-29 05:50
Exactly!

**Comment by kfoozminus** [comment] 2019-05-29 05:54
Ok, thanks. I'm trying to reproduce this with load testing and restarting the backend pods over and over.

**Comment by kfoozminus** [comment] 2019-05-29 07:40
@mcasperson @mkozjak While we are trying to understand what's the problem - if this problem happens again - maybe we can arrange a virtual meeting to see what's going wrong.

**Comment by mkozjak** [comment] 2019-05-29 08:04
Yes, that'd be great.

**Comment by kfoozminus** [comment] 2019-05-29 09:32
@mkozjak Are you using the default alpine based haproxy-image or did you specify `--haproxy-image-tag` while installing voyager?

**Comment by mkozjak** [comment] 2019-05-29 11:07
@kfoozminus 
```
helm install appscode/voyager --name voyager-operator --version 9.0.0 \
--namespace kube-system --set cloudProvider=gke \
--set apiserver.enableValidatingWebhook=false
```

**Comment by mkozjak** [comment] 2019-05-30 11:28
@kfoozminus Want me to upgrade to 10.x?

**Comment by kfoozminus** [comment] 2019-05-31 04:53
No it's ok.

**Comment by mkozjak** [comment] 2019-06-03 08:38
@kfoozminus Note that I'll soon need to update to 10.x so maybe try running tests on that version also.

**Comment by mkozjak** [comment] 2019-06-03 14:21
@kfoozminus I'm having a reproduced issue currently. Anyway to do a live debugging session together? I will need to restart everything in half an hour..

**Comment by mkozjak** [comment] 2019-06-03 14:23
@mcasperson What did you do to tackle this one in the mean time?

**Comment by mkozjak** [comment] 2019-06-03 14:59
@kfoozminus Upgraded to 10.x, I guess.
```sh
kubectl exec -it voyager-voyager-operator-76778cc5f9-4ctln -n kube-system voyager version

Version = 10.0.0
VersionStrategy = tag
Os = alpine
Arch = amd64
CommitHash = b866601fd012b57feb048e8eb3caa954ae5280af
GitBranch = release-10.0
GitTag = 10.0.0
CommitTimestamp = 2019-04-29T00:07:03
```

A really confusing part is:
```
kubectl describe pod voyager-k8s-ingress-66f7d879fd-2lfv9

Image:         appscode/haproxy:1.9.2-9.0.0-alpine
```

Shouldn't it be `appscode/haproxy:1.9.6-10.0.0-alpine`?

**Comment by kfoozminus** [comment] 2019-06-03 19:29
@mkozjak sorry I wasn't online. The problem ia gone by now, I guess? :(

**Comment by mkozjak** [comment] 2019-06-03 19:31
Yup.

**Comment by tamalsaha** [comment] 2019-06-03 21:08
Hi Mario,
Our offices are closed this week for Eid vacation. We will be back to
regular schedule from next Monday (June 10). We are going to pick up this
issue once we are back.

Regards,
Tamal

**Comment by lanserver** [comment] 2019-06-05 20:48
Hey everyone, just wanted to mention that I'm having a very similar issue, if not the same exact issue. Everything works great until large amounts of traffic are moved through the ingress, then the ingress will continue working properly for 10-15 minutes before intermittently throwing 503s.

I'm using Azure Kubernetes Service 1.14.0 running Voyager 10 pointed at external backends (Azure app services). Nothing else is having trouble reaching these services when we see this issue. Unfortunately, I'm unable to confirm whether this issue scales out in the same way since I'm only able to replicate the issue in prod. If there's anything I can do to help with this issue, I'm happy to help.

**Comment by lanserver** [comment] 2019-06-12 19:25
Hey guys, just curious if you have any updates on this issue. Thanks!

**Comment by kfoozminus** [comment] 2019-06-12 19:35
We are assuming for now that this issue is happening because of haproxy reload issue and pods being terminated without grace. I'm writing a detailed doc about it. But we've only been able to reproduce this issue in where after a certain while it goes away. (Basically we are assuming no 503 for new requests.)

Are you facing this problem right now?

**Comment by lanserver** [comment] 2019-06-12 19:42
Yes, we're able to reproduce this issue any time we ramp up traffic to our ingress. We have it down for the time being but I can bring it back up if you need something.

**Comment by kfoozminus** [comment] 2019-06-12 19:47
Yes, that'd be great. Join our slack: https://appscode.slack.com/

**Comment by lanserver** [comment] 2019-06-12 20:04
Great, thanks! Just messaged you over there.

**Comment by mkozjak** [comment] 2019-06-13 11:06
@kfoozminus @lanserver Maybe any updates on this one? In which slack channel did you do the debugging in not in a direct message?

**Comment by kfoozminus** [comment] 2019-06-13 12:01
@mkozjak we used direct message.
His issue seems different from this though.

**Comment by mkozjak** [comment] 2019-06-13 12:09
@kfoozminus So it was something different than sudden 503s after certain pods die and 200s after the ingress controller pods are restarted?

**Comment by kfoozminus** [comment] 2019-06-13 12:12
Yeah.

**Comment by mkozjak** [comment] 2019-06-13 12:35
Well, ok. The next time I reproduce the issue I'm gonna try sending SIGUSR2 signal to a haproxy process so it reloads its configuration in runtime to see if that'll solve the issue.
Can you please continue your tests on this internally, @kfoozminus?

**Comment by kfoozminus** [comment] 2019-06-13 13:00
@mkozjak Yes, of course! We are testing and trying to reproduce this continuously!
Were you able to see how many haproxy process was running in that moment?

**Comment by mkozjak** [comment] 2019-06-13 13:12
@kfoozminus In one pod or you mean the number of pods? It was 4 running pods at the time.

**Comment by kfoozminus** [comment] 2019-06-14 06:22
Next time it happens again, give us the output to `ps aux | grep haproxy` from inside the voyager pod. Want to see how many haproxy processes were running.
I hope to do a live session though.

**Comment by kfoozminus** [comment] 2019-06-19 10:48
> kubectl describe pod voyager-k8s-ingress-66f7d879fd-2lfv9
> 
> Image:         appscode/haproxy:1.9.2-9.0.0-alpine
> 
> Shouldn't it be `appscode/haproxy:1.9.6-10.0.0-alpine`?

@mkozjak yes, it should be. What exact command did you use to upgrade to 10.0.0?

**Comment by mkozjak** [comment] 2019-06-19 12:49
@kfoozminus
```helm upgrade voyager-operator appscode/voyager --version 10.0.0 --namespace kube-system --set cloudProvider=gke --set apiserver.enableValidatingWebhook=false```

**Comment by mkozjak** [comment] 2019-06-24 07:47
@kfoozminus: Maybe I did something wrong with the update procedure?

**Comment by kfoozminus** [comment] 2019-06-25 06:34
I upgraded with same command. Mine shows `appscode/haproxy:1.9.6-10.0.0-alpine`.
Does yours still show `appscode/haproxy:1.9.2-9.0.0-alpine`?

**Comment by mkozjak** [comment] 2019-06-25 06:36
Seems to have managed to pull the latest one in the end, since I restart the ingress all the time.

`appscode/haproxy:1.9.6-10.0.0-alpine`

**Comment by kfoozminus** [comment] 2019-06-25 06:39
After upgrading, it takes a few seconds to update the image (time new voyager operator takes to go into running state and update all ingress deployments).

**Comment by mkozjak** [comment] 2019-07-10 10:23
@kfoozminus: Maybe had any luck reproducing the issue?

**Comment by Simon3** [comment] 2019-08-05 08:59
Hi, it seems like the issue is still present in version 10.0.0. I got several 503 errors on frontend files today right after upgrading my stack, and killing the Voyager pod solved the issue.

**Comment by mkozjak** [comment] 2019-08-05 09:50
@Simon3: next time you reproduce, can you please try running ps aux | grep haproxy and sending SIGUSR2 to the process inside the pod instead of killing it and see if it'll start working again? Thanks!

**Comment by Simon3** [comment] 2019-08-05 10:23
Sure I will if it happens again.

**Comment by Simon3** [comment] 2019-10-02 15:54
Hey, I'm still on Voyager 10.0.0 and the bug keeps occurring, like twice a month. We are doing lots of helm upgrades though, like 20 per day. I tried the SIGUSR2 signal, but it didn't change anything, here is my history in case I would have missed something: 

```
bash-4.4# ps | grep haproxy
    9 root      0:00 runsv haproxy-controller
   12 root     43:03 voyager haproxy-controller --enable-analytics=true --burst=1000000 --cloud-provider=gke --ingress-api-version=voyager.appscode.com/v1beta1 --ingress-name=flowr-527-rc-latest-ingress --qps=1e+06 --logtostderr=false --alsologtostderr=false --v=3 --stderrthreshold=0
 1002 root      0:10 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid
 1051 root      0:03 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -x /var/run/haproxy.sock -sf 1048
 1057 root      0:01 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -x /var/run/haproxy.sock -sf 1054
bash-4.4# 
bash-4.4# kill -SIGUSR2 12
```

It would be nice if we could get an update on this issue, is there a point in upgrading to v11.0.1 for this issue? Are you still investigating it? 

Thanks in advance!

**Comment by rmohammed-xtime** [comment] 2020-01-10 19:15
@Simon3 I believe the SIGUSR2 needs to go to the haproxy processes and not the voyager wrapper

@kfoozminus Is there an update on this issue?

**Comment by Simon3** [comment] 2020-02-19 09:56
Ok I applied it to every haproxy process this time, still lots of 503 errors. 
I then deleted the Voyager pod, and it worked like a charm as usual.

**Comment by elynnyap** [comment] 2020-02-20 17:55
We are seeing the same issue on version 11.0.0. Every release, one or two Voyager pods (out of 65) will flood 5xx errors. Each of those affected Voyager pods has two `haproxy` processes running, as opposed to one `haproxy` process on the normal Voyager pods.

```
bash-4.4# ps aux | grep haproxy

10 root 0:00 runsv haproxy-controller

12 root 7:40 voyager haproxy-controller --enable-analytics=true --burst=1000000 --cloud-provider=gke --ingress-api-version=voyager.appscode.com/v1beta1 --ingress-name=rlcdn --qps=1e+06 --logtostderr=false --alsologtostderr=false --v=3 --stderrthreshold=0

8437 root 13:31 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -x /var/run/haproxy.sock -sf 8434

8461 root 6:04 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -x /var/run/haproxy.sock -sf 8458

8469 root 0:00 grep haproxy
```
Issuing `SIGUSR2` doesn't work; however issuing `SIGKILL` to the *older* process (`8437` in the example above) works. Issuing `SIGKILL` to the newer process will just cause another `haproxy` process to spawn and the errors to continue.

Another observation is that right before the errors begin, the affected Voyager pods log errors like these:

```
E0213 18:32:18.845822      12 controller.go:276] error reading haproxy.pid file: open /var/run/haproxy.pid: no such file or directory
```

```
E0123 00:04:52.399698      12 controller.go:274] error reading haproxy.pid file: EOF
```

Those errors are thrown from [here](https://github.com/appscode/voyager/blob/release-11.0/pkg/haproxy/controller/reload.go#L35). My guess as to what's happening is that for whatever reason, `/var/run/haproxy.pid` does not properly capture the pid of a running `haproxy` process, so the [controller starts a new one](https://github.com/appscode/voyager/blob/0304c17109cf06de3c673a40be75321e55667592/pkg/haproxy/controller/reload.go#L96-L98) when it actually should just reload the already-running process.

**Comment by aaronbbrown** [comment] 2021-04-19 19:27
Is there any update on this? We're interested in rolling this out to production and are encountering this same problem. Any possibility #1547 can get merged or something similar? 

cc: @Simon3

**Comment by Simon3** [comment] 2021-04-19 21:29
The bug has not occurred in any of my K8s clusters since I rolled #1547 upgrade, but I have no news about a possible merge, sorry.

**Closed** 2021-04-22 23:13 UTC
